map all from host to vm

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -13,6 +13,7 @@ jobs:
       image: ghcr.io/kiracore/docker/base-image:v0.0.2.0
       volumes:
         - /var/run/docker.sock:/var/run/docker.sock
+        - /:/host
     steps:
           - name: Checking dependency versions
             run: |
@@ -27,6 +28,7 @@ jobs:
             working-directory: ${{ env.RUNNER_WORKSPACE }}
             run: |
               ls -l || echo "NOT FOUND (current dir): $PWD"
+              ls -l /host || echo "NOT FOUND: /host"
               ls -l $GITHUB_WORKSPACE || echo "NOT FOUND (GITHUB_WORKSPACE): $GITHUB_WORKSPACE"
               ls -l $HOME || echo "NOT FOUND (HOME): $HOME"
               ls -l /github/home || echo "NOT FOUND: /github"
@@ -38,6 +40,8 @@ jobs:
               ls -l $RUNNER_TOOL_CACHE || echo "NOT FOUND (RUNNER_TOOL_CACHE): $RUNNER_TOOL_CACHE"
               ls -l $RUNNER_WORKSPACE || echo "NOT FOUND (RUNNER_WORKSPACE): $RUNNER_WORKSPACE"
               ls -l $GITHUB_STEP_SUMMARY || echo "NOT FOUND (GITHUB_STEP_SUMMARY): $GITHUB_STEP_SUMMARY"
+              ls -l $RUNNER_WORKSPACE/interx || echo "NOT FOUND (RUNNER_WORKSPACE/interx): $RUNNER_WORKSPACE/interx"
+              ls -l $GITHUB_STEP_SUMMARY/interx || echo "NOT FOUND (GITHUB_STEP_SUMMARY/interx): $GITHUB_STEP_SUMMARY/interx"
               make install
               interxd version
               ls -l
